// try {
//   const b = 17;
//   b = 18;
//   console.log(b);
// } catch (err) {
//   console.log(err);
// }

try {
  throw ("Lol !this is custom error");
} catch {
  console.log("ok");
}
